---
- name: REBOOT | Flush notified handlers
  ansible.builtin.meta: flush_handlers

- name: REBOOT | Check the uptime prior reboot
  ansible.builtin.shell:
    cmd: uptime
  register: UPTIME_PRE_REBOOT

- name: REBOOT | Uptime remote machine
  ansible.builtin.debug:
    msg: "{{ UPTIME_PRE_REBOOT.stdout }}"

- name: REBOOT | Reboot the machine
  ansible.builtin.shell:
    cmd: "(sleep {{ reboot_delay }} && {{ reboot_command }} &)" # noqa 301 This was before the reboot module existed.
  async: 1
  poll: 0
  ignore_errors: yes

- name: REBOOT | Waiting respons machine
  block:
    - name: REBOOT | 1. wait for the start of reboot
      ansible.builtin.pause:
        seconds: "{{ reboot_delay }}"

    - name: REBOOT | 2. wait for the machine to be up
      ansible.builtin.wait_for:
        port: "{{ ansible_port | default('22') }}"
        host: "{{ (ansible_ssh_host | default(ansible_host) | default(inventory_hostname)) }}"
        connect_timeout: "{{ reboot_connect_timeout }}"
        sleep: "{{ reboot_wait_sleep }}"
        delay: "{{ reboot_wait_delay }}"
        timeout: "{{ reboot_wait_timeout }}"
      connection: local
      when:
        - ansible_connection is defined
        - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

  become: false
  when: reboot_wait

- name: REBOOT | Interval before next task
  become: no
  ansible.builtin.pause:
    seconds: "{{ reboot_interval_seconds }}"
  when: reboot_interval
